export enum ConfigEnum {
  NODE_ENV = 'NODE_ENV',
  HOST = 'HOST',
  PORT = 'PORT',
  GLOBAL_PREFIX = 'GLOBAL_PREFIX',
  SECRET = 'SECRET',
  TOKEN_TIMEOUT = 'TOKEN_TIMEOUT',
  CHAT_TOKEN_SECRET = 'CHAT_TOKEN_SECRET',
  ALLOWED_ORIGINS = 'ALLOWED_ORIGINS',
  PUBLIC_FOLDER_PATH = 'PUBLIC_FOLDER_PATH',
  WATERMARK = 'WATERMARK',
  FRONT_URL = 'FRONT_URL',

  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_PORT = 'DATABASE_PORT',
  DATABASE_USERNAME = 'DATABASE_USERNAME',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  DATABASE_NAME = 'DATABASE_NAME',
  DATABASE_SCHEMA = 'DATABASE_SCHEMA',

  WT_SIGN_ALGORITHM = 'JWT_SIGN_ALGORITHM',
  JWT_EXPIRE = 'JWT_EXPIRE',
  JWT_REFRESH_EXPIRE = 'JWT_REFRESH_EXPIRE',
  JWT_PUBLIC = 'JWT_PUBLIC',
  JWT_PRIVATE = 'JWT_PRIVATE',

  EMAIL_FROM = 'EMAIL_FROM',
  EMAIL_HOST = 'EMAIL_HOST',
  EMAIL_USER = 'EMAIL_USER',
  EMAIL_PASSWORD = 'EMAIL_PASSWORD',

  SENDGRID_API_KEY = 'SENDGRID_API_KEY',
}
